### PR TITLE
Create Algorithm: MergeSort - Python

### PR DESCRIPTION
**Pull request by knekvasil**

### CODE REVIEW

**Review by Isha307 — CHANGES_REQUESTED** [review]
make it user interactive

**Comment by knekvasil** [comment]
Let me know if these changes were sufficient

**Review by Isha307 — COMMENTED** [review]
Your algorithm is not sorting the number, I think there might be some error while taking input.

**Comment by knekvasil** [comment]
Bug squashed. Elements in array were being evaluated as strings, not ints.

**Review by Isha307 — APPROVED** [review]

**Pull request merged**
